FORMAT: 1A
HOST: https://xmetrics.shaftsoft.ru/

# Metrics API (Version 1)

Sample API to explore functionality of *Apiary* and *API Blueprints Spec*.

## Common Definitions

This section describe common concepts used in all API calls.

### MetricID Structure
`MetricID` – fully qualfied metric name, with all its tags, has the following format:

`Namespace`.`MetricName`.`[Name1:Value1]`.`[Name2:Value2]`. *...* .`[NameN:ValueN]` where,

* `Namespace` – prefix used to partition metrics space
* `MetricName` – name of the sensor that emits value
* `[NameN:ValueN]` – tag, used to de-dupe metric

# Group Storing & Retrieval of Datapoints

These API calls work with datapoints.
Full `MetricID` must be specified in every call.

## Datapoints API [/v1/datapoints]

### Publish Datapoints [POST]

#### Input JSON Description
| Name | Description | Details |
| ---- | ----------- | ------- |
| value | Value of datapoint | required |
| id | `MetricID` of a datapoint | required |
| timestamp | UNIX Timestamp. If not present, current server's time used | optional |

#### Output JSON Description
| Name | Description | Details |
| ---- | ----------- | ------- |
| value | Value of datapoint | required |

#### Errors Description
| Name | Description | Details |
| ---- | ----------- | ------- |
| value | Value of datapoint | required |

+ Request (application/json)

    + Body

            [
                {
                    "timestamp": 213,
                    "value": 123,
                    "id": "Namespace.MetricName$[d1:v1][d2:v2]"
                }
            ]
            
    + Schema
    
            {
                "type": "array",
                "items": {
                    "properties": {
                        "timestamp": {
                            "type": ["date-time", "null"],
                            "required": false
                        },
                        "id": {
                            "type": "number",
                            "required": true
                        },
                        "value": {
                            "type": "number",
                            "required": true
                        }
                    }
                }
            }

+ Response 200 (application/json)
  
    + Body
    
            {
                "status": "OK",
                "metrics_created": false
            }

    + Schema

            {}
            