FORMAT: 1A

# Metrics API v1
Sample API to explore functionality of *Apiary* and *API Blueprints*.

## MetricID Structure
`MetricID` – fully qualfied metric name, with all its dimensions, has the following format:

`Namespace`.`MetricName`.`[Name1:Value1]`.`[Name2:Value2]`. *...* .`[NameN:ValueN]`

where,

* `Namespace` – prefix used to partition metrics space
* `MetricName` – name of the sensor that emits value
* `[NameN:ValueN]` – tag, used to de-dupe metric

# Group Publishing & Retriveving Metrics
These API calls operate directly on metrics.
Full `MetricID` must be specified in every call.

## Metrics [/metrics]

+ Parameters
    - timestamp (optional, number) UNIX Timestamp of measurement
    
        If not specified current time on the server will be used.
        **NOTE:** timestamp will be rounded to previous minute.

    - value (required, double) Value of measurement
    
        IEEE754 format, NaNs, not allowed.

    - id (required, string) MetricID to which publish the measurement.
    
        if MetricID does not exists on the system, it will be created.

### Publish metrics [POST]

+ Request (application/json)

    [
        {
            "timestamp": 213,
            "value": 123,
            "id": "Namespace.MetricName$[d1:v1][d2:v2]"
        }
    ]

+ Response 200 (application/json)
    
    {"status": "OK", "metrics_created": false}
